// Code generated by "stringer -type=_TextConvertTo -nameConvertToCase=snake_case -trimprefix=_TextConvertTo -output=text_transform_stringy_string.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_TextConvertToNone-0]
	_ = x[_TextConvertToCamelCase-1]
	_ = x[_TextConvertToSnakeCase-2]
	_ = x[_TextConvertToKebabCase-3]
}

const __TextConvertTo_name = "nonecamel_casesnake_casekebab_case"

var __TextConvertTo_index = [...]uint8{0, 4, 14, 24, 34}

func (i _TextConvertTo) String() string {
	if i < 0 || i >= _TextConvertTo(len(__TextConvertTo_index)-1) {
		return "_TextConvertTo(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return __TextConvertTo_name[__TextConvertTo_index[i]:__TextConvertTo_index[i+1]]
}
