// Code generated by "go-stringer -type=TwoTypeFirst,TwoTypeSecond -trimprefix=@me -nametransform=snake_case_lower -outputtransform=snake_case_lower"; DO NOT EDIT.

package sample

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TwoTypeFirstFirst-0]
	_ = x[TwoTypeFirstSecond-2]
	_ = x[TwoTypeFirstThird-4]
	_ = x[TwoTypeFirstFourth-6]
	_ = x[TwoTypeFirstFifth-8]
	_ = x[TwoTypeFirstSixth-10]
	_ = x[TwoTypeFirstSeventh-12]
	_ = x[TwoTypeFirstEighth-14]
	_ = x[TwoTypeFirstNinth-16]
	_ = x[TwoTypeFirstTenth-18]
}

const (
	_TwoTypeFirst_name_0 = "first"
	_TwoTypeFirst_name_1 = "second"
	_TwoTypeFirst_name_2 = "third"
	_TwoTypeFirst_name_3 = "fourth"
	_TwoTypeFirst_name_4 = "fifth"
	_TwoTypeFirst_name_5 = "sixth"
	_TwoTypeFirst_name_6 = "seventh"
	_TwoTypeFirst_name_7 = "eighth"
	_TwoTypeFirst_name_8 = "ninth"
	_TwoTypeFirst_name_9 = "tenth"
)

func (i TwoTypeFirst) String() string {
	switch {
	case i == 0:
		return _TwoTypeFirst_name_0
	case i == 2:
		return _TwoTypeFirst_name_1
	case i == 4:
		return _TwoTypeFirst_name_2
	case i == 6:
		return _TwoTypeFirst_name_3
	case i == 8:
		return _TwoTypeFirst_name_4
	case i == 10:
		return _TwoTypeFirst_name_5
	case i == 12:
		return _TwoTypeFirst_name_6
	case i == 14:
		return _TwoTypeFirst_name_7
	case i == 16:
		return _TwoTypeFirst_name_8
	case i == 18:
		return _TwoTypeFirst_name_9
	default:
		return "TwoTypeFirst(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TwoTypeSecondFirst-0]
	_ = x[TwoTypeSecondSecond-1]
	_ = x[TwoTypeSecondThird-2]
	_ = x[TwoTypeSecondFourth-3]
	_ = x[TwoTypeSecondFifth-4]
	_ = x[TwoTypeSecondSixth-5]
	_ = x[TwoTypeSecondSeventh-6]
	_ = x[TwoTypeSecondEighth-7]
	_ = x[TwoTypeSecondNinth-8]
	_ = x[TwoTypeSecondTenth-9]
}

const _TwoTypeSecond_name = "firstsecondthirdfourthfifthsixthseventheighthninthtenth"

var _TwoTypeSecond_index = [...]uint8{0, 5, 11, 16, 22, 27, 32, 39, 45, 50, 55}

func (i TwoTypeSecond) String() string {
	if i >= TwoTypeSecond(len(_TwoTypeSecond_index)-1) {
		return "TwoTypeSecond(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TwoTypeSecond_name[_TwoTypeSecond_index[i]:_TwoTypeSecond_index[i+1]]
}
