// Code generated by "stringer -target=D:\GitHubRepos\go-stringer\sample\enum_updateable_field.go -type=UpdateableField -linecomment=true"; DO NOT EDIT.

package sample

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Title-0]
	_ = x[ReleaseStatus-1]
	_ = x[LastCheckedDate-2]
	_ = x[CreatedDate-3]
	_ = x[UpdatedDate-4]
	_ = x[TorrentFilesSize-5]
	_ = x[Notes-6]
	_ = x[Identifier-7]
}

const _UpdateableField_name = "update_titlerelease_statusLastCheckedDateCreatedDateUpdatedDateTorrentFilesSizeNotesIdentifier"

var _UpdateableField_index = [...]uint8{0, 12, 26, 41, 52, 63, 79, 84, 94}

func (i UpdateableField) String() string {
	if i >= UpdateableField(len(_UpdateableField_index)-1) {
		return "UpdateableField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UpdateableField_name[_UpdateableField_index[i]:_UpdateableField_index[i+1]]
}
