// Code generated by "stringer -target=D:\GitHubRepos\go-stringer\sample\enum_updateable_field.go -type=UpdateableField -linecomment=false -trimprefix=UpdateableField -nameConvertToCase=snake_case"; DO NOT EDIT.

package sample

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UpdateableFieldTitle-0]
	_ = x[UpdateableFieldReleaseStatus-1]
	_ = x[UpdateableFieldLastCheckedDate-2]
	_ = x[UpdateableFieldCreatedDate-3]
	_ = x[UpdateableFieldUpdatedDate-4]
	_ = x[UpdateableFieldTorrentFilesSize-5]
	_ = x[UpdateableFieldNotes-6]
	_ = x[UpdateableFieldIdentifier-7]
}

const _UpdateableField_name = "titlerelease_statuslast_checked_datecreated_dateupdated_datetorrent_files_sizenotesidentifier"

var _UpdateableField_index = [...]uint8{0, 5, 19, 36, 48, 60, 78, 83, 93}

func (i UpdateableField) String() string {
	if i >= UpdateableField(len(_UpdateableField_index)-1) {
		return "UpdateableField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UpdateableField_name[_UpdateableField_index[i]:_UpdateableField_index[i+1]]
}
